import type { EquipmentItem, QuotationRequest } from '../types/marketplace';

export const mockEquipmentCatalog: EquipmentItem[] = [
  // =========================================================================
  // MEDICAL EQUIPMENT (11 ITEMS)
  // =========================================================================
  {
    id: 'EQ-MED-001',
    name: 'MAGNETOM Free.Max Whole-Body MRI System (0.55T High-V)',
    modelNumber: 'MAG-FREE-055',
    category: 'MEDICAL',
    subcategory: 'Diagnostic Imaging',
    manufacturer: 'Siemens Healthineers',
    originCountry: 'Germany',
    description: 'Helium-free 0.55T High-V MRI system with 80cm patient bore. Designed for accessible whole-body imaging, low siting costs, and high clinical diagnostic throughput in decentralized healthcare centers and community clinics.',
    keySpecifications: [
      '80 cm patient bore for patient comfort and bariatric access',
      'DryCool helium-free technology with sealed magnet cooling',
      'Deep Resolve reconstruction algorithm',
      'Low power consumption (< 25 kW average operational load)',
      'High-performance gradient system: 26 mT/m at 45 T/m/s',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485', 'IEC 60601-1-2'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 12,
    leadTimeWeeks: 6,
    warrantyYears: 3,
    powerRequirements: '400V 3-Phase, 50Hz, 35kVA',
    dimensions: '185 x 215 x 205 cm',
    weightKg: 3200,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-002',
    name: 'Voluson E10 Expert 4D/HDlive Diagnostic Ultrasound',
    modelNumber: 'VOLUSON-E10-EXP',
    category: 'MEDICAL',
    subcategory: 'Diagnostic Imaging',
    manufacturer: 'GE Healthcare',
    originCountry: 'United States',
    description: 'Premier women\'s health and cardiovascular ultrasound console with Radiance System Architecture, electronic 4D Matrix probe compatibility, and HDlive silhouette rendering.',
    keySpecifications: [
      '23-inch High-Resolution OLED widescreen monitor',
      'Electronic 4D Matrix matrix transducer technology (eM6C)',
      'HDlive Studio 3D/4D lighting and anatomical depth enhancement',
      'SonoL&D automated labor progress assessment algorithms',
      '4 active probe ports with motorized height-adjustable console',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'US FDA 510(k)', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 2,
    warrantyYears: 2,
    powerRequirements: '220-240V, 50/60Hz, 1000VA',
    dimensions: '148 x 58 x 93 cm',
    weightKg: 135,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-003',
    name: 'DigitalDiagnost C90 High-Throughput Digital Radiography System',
    modelNumber: 'DD-C90-PRO',
    category: 'MEDICAL',
    subcategory: 'Diagnostic Imaging',
    manufacturer: 'Philips Healthcare',
    originCountry: 'Netherlands',
    description: 'Ceiling-suspended digital radiography system with live camera positioning, Eleva user interface, and UNIQUE 2 image processing for ultra-fast thoracic, musculoskeletal, and abdominal imaging.',
    keySpecifications: [
      'Wireless SkyPlate Cesium Iodide (CsI) digital flat panel detectors',
      'Live tube-head camera for precise zero-repeat patient positioning',
      'UNIQUE 2 multi-frequency image enhancement engine',
      'Motorized auto-tracking detector stand and ceiling suspension',
      'DoseAware integrated radiation dose management',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485', 'IEC 60601-2-54'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 24,
    leadTimeWeeks: 4,
    warrantyYears: 3,
    powerRequirements: '400V 3-Phase, 50Hz, 80kW generator',
    dimensions: 'Ceiling mounted track: 400 x 300 cm',
    weightKg: 850,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-004',
    name: 'Aquilion Prime SP 160-Slice Multi-Slice CT Scanner',
    modelNumber: 'AQUILION-SP160',
    category: 'MEDICAL',
    subcategory: 'Diagnostic Imaging',
    manufacturer: 'Canon Medical Systems',
    originCountry: 'Japan',
    description: 'Ultra-low dose 160-slice CT scanner equipped with AiCE Deep Learning Reconstruction, 78cm gantry aperture, and rapid 0.35-second rotation speed for emergency, cardiac, and oncology scans.',
    keySpecifications: [
      '160 slices per gantry rotation with 0.5mm detector elements',
      'AiCE (Advanced Intelligent Clear-IQ Engine) deep learning reconstruction',
      '78 cm large gantry opening with SEMAR metal artifact reduction',
      '7.5 MHU Megacool X-ray tube for continuous high-load scanning',
      '300 kg heavy-duty patient couch with lateral table shift',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 24,
    leadTimeWeeks: 8,
    warrantyYears: 3,
    powerRequirements: '400V 3-Phase, 50Hz, 100kVA',
    dimensions: 'Gantry: 235 x 95 x 198 cm',
    weightKg: 2100,
    availability: 'REQUEST_SOURCING',
  },
  {
    id: 'EQ-MED-005',
    name: 'BeneVision N17 Multi-Parameter Patient Monitor',
    modelNumber: 'BENEV-N17-ICU',
    category: 'MEDICAL',
    subcategory: 'Monitoring & Critical Care',
    manufacturer: 'Mindray Medical',
    originCountry: 'China / Germany',
    description: 'High-acuity 18.5-inch capacitive touchscreen patient monitor for ICU, HDU, and Emergency departments. Features multi-parameter modular slots and central telemetry integration.',
    keySpecifications: [
      '18.5" anti-glare capacitive multi-touch clinical display',
      'Standard ECG (3/5/12-lead), SpO2, NIBP, Dual Temp, Invasive BP',
      'Optional modules: EtCO2, Cardiac Output, BIS, Neuromuscular Transmission',
      'Integrated BeneLink HL7 interface for direct EMR/PACS telemetry',
      'Fanless thermal design for quiet, infection-safe operation',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485', 'IEC 60601-1-8'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 3,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    powerRequirements: '100-240V AC, 50/60Hz, 150W with 4-hr battery backup',
    dimensions: '42 x 20 x 36 cm',
    weightKg: 8.5,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-006',
    name: 'Infusomat Space Volumetric Infusion Pump',
    modelNumber: 'INFUSO-SPACE-V3',
    category: 'MEDICAL',
    subcategory: 'Monitoring & Critical Care',
    manufacturer: 'B. Braun',
    originCountry: 'Germany',
    description: 'Compact, stackable volumetric infusion pump for standard infusions, TCI/TIVA anesthesia, enteral nutrition, and blood transfusions with DoseGuard medication safety database.',
    keySpecifications: [
      'Infusion rate: 0.1 to 1200 ml/h with high volumetric precision',
      'DoseGuard custom drug library with hard and soft dosage limits',
      'Integrated ultrasonic air-in-line detector and upstream pressure sensor',
      'SpaceStation multi-rack docking compatible with wireless data transfer',
      'Drop and splash resistant clinical casing (IP22 rating)',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 1,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    powerRequirements: '100-240V AC with 8-hr internal rechargeable battery',
    dimensions: '21.4 x 6.8 x 12.4 cm',
    weightKg: 1.4,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-007',
    name: 'R Series ALS Clinical Defibrillator & Monitor',
    modelNumber: 'ZOLL-R-ALS',
    category: 'MEDICAL',
    subcategory: 'Emergency & Resuscitation',
    manufacturer: 'ZOLL Medical',
    originCountry: 'United States',
    description: 'Advanced Life Support (ALS) monitor/defibrillator with Real CPR Help, See-Thru CPR artifact filtering, manual defibrillation, and external transcutaneous pacing for emergency and trauma wards.',
    keySpecifications: [
      'Real CPR Help real-time audio and visual depth and rate feedback',
      'See-Thru CPR technology filters ECG during chest compressions',
      'OneStep cable system for combined pacing, cardioversion, and ECG',
      'Automated daily self-testing of clinical parameters',
      '3-lead / 5-lead ECG monitoring with pulse oximetry (SpO2)',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'US FDA', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 3,
    leadTimeWeeks: 2,
    warrantyYears: 3,
    powerRequirements: '100-240V AC / 12V DC Smart Lithium-ion battery (6-hr run)',
    dimensions: '31 x 27 x 23 cm',
    weightKg: 6.8,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-008',
    name: 'Fabius Tiro Anesthesia Workstation',
    modelNumber: 'FABIUS-TIRO-PLUS',
    category: 'MEDICAL',
    subcategory: 'Surgical & Procedures',
    manufacturer: 'Dräger Medical',
    originCountry: 'Germany',
    description: 'High-performance compact anesthesia workstation for procedure suites and day surgery centers with electrically driven piston ventilator and multi-gas monitoring.',
    keySpecifications: [
      'E-vent electrically driven, electronically controlled piston ventilator',
      'Ventilation modes: VCV, PCV, Pressure Support (PS), and Manual/Spontaneous',
      'Dual Selectatec vaporizer mounting bar with interlock system',
      'Integrated compact breathing system with heated absorber option',
      'High-contrast color LCD display with digital fresh gas flow indicators',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485', 'IEC 60601-2-13'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 12,
    leadTimeWeeks: 4,
    warrantyYears: 2,
    powerRequirements: '100-240V AC, 50/60Hz with internal emergency backup',
    dimensions: '136 x 58 x 66 cm',
    weightKg: 110,
    availability: 'UNAVAILABLE',
  },
  {
    id: 'EQ-MED-009',
    name: 'EVIS X1 CV-1500 Video Endoscopy System Console',
    modelNumber: 'OLY-EVIS-X1',
    category: 'MEDICAL',
    subcategory: 'Diagnostic & Endoscopy',
    manufacturer: 'Olympus',
    originCountry: 'Japan',
    description: 'Flagship endoscopic imaging center console featuring Texture and Color Enhancement Imaging (TXI), Red Dichromatic Imaging (RDI), and Narrow Band Imaging (NBI) for advanced gastrointestinal diagnostics.',
    keySpecifications: [
      'TXI (Texture & Color Enhancement) optimizes brightness, texture, and tone',
      'RDI (Red Dichromatic Imaging) visualizes deep bleeding vessels during intervention',
      'NBI (Narrow Band Imaging) for high-contrast microvascular mucosal evaluation',
      '4K UHD digital video output with integrated touch-screen user control',
      'Compatible with EVIS EXERA III and EVIS X1 series endoscopes',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 3,
    warrantyYears: 2,
    powerRequirements: '220-240V AC, 50Hz, 300VA',
    dimensions: '37 x 49 x 19 cm',
    weightKg: 21,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-010',
    name: 'Maquet Alphamaquet 1150 Mobile Operating Table',
    modelNumber: 'MAQUET-ALPHA-1150',
    category: 'MEDICAL',
    subcategory: 'Surgical & Procedures',
    manufacturer: 'Getinge',
    originCountry: 'Sweden / Germany',
    description: 'Universal electro-hydraulic operating table with modular interchangeable table tops, high weight capacity (450 kg), and 360-degree C-arm radiolucent access for clinical procedures.',
    keySpecifications: [
      'Maximum patient load capacity: 450 kg in balanced anatomical position',
      'Height adjustment range: 600 mm to 1050 mm with motorized longitudinal shift',
      'Trendelenburg / Reverse Trendelenburg: ±30°, Lateral tilt: ±20°',
      'Special Foam Core pressure-relieving pads',
      'Dual wireless remote control + auxiliary column backup controller',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 3,
    warrantyYears: 3,
    powerRequirements: '100-240V AC with internal heavy-duty gel batteries',
    dimensions: '210 x 59 x 60-105 cm',
    weightKg: 280,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-MED-011',
    name: 'Mobile C-Arm Fluoroscopy Imaging System',
    modelNumber: 'CARM-FLUO-900',
    category: 'MEDICAL',
    subcategory: 'Diagnostic Imaging',
    manufacturer: 'Ziehm Imaging',
    originCountry: 'Germany',
    description: 'Compact high-frequency mobile C-arm system with flat-panel detector technology for orthopedic, vascular, and general surgical fluoroscopy in procedure suites.',
    keySpecifications: [
      '30 x 30 cm flat-panel detector with high dynamic resolution',
      'SmartDose radiation reduction package',
      'Motorized orbital movement with 165° rotation range',
      'Touchscreen monitor cart with dual split displays',
      'DICOM 3.0 seamless PACS connectivity',
    ],
    complianceStandards: ['MDA Approved', 'CE Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 4,
    warrantyYears: 2,
    powerRequirements: '220-240V AC, Single Phase, 16A',
    dimensions: '190 x 85 x 175 cm',
    weightKg: 310,
    availability: 'REQUEST_SOURCING',
  },

  // =========================================================================
  // NON-MEDICAL HEALTHCARE EQUIPMENT (10 ITEMS)
  // =========================================================================
  {
    id: 'EQ-NON-001',
    name: 'Progressa+ Advanced ICU Therapy Smart Healthcare Bed',
    modelNumber: 'HILL-PROG-ICU',
    category: 'NON_MEDICAL',
    subcategory: 'Ward & Furniture',
    manufacturer: 'Hill-Rom / Baxter',
    originCountry: 'United States',
    description: 'High-acuity medical-surgical bed with integrated continuous lateral rotation therapy (CLRT), percussion & vibration, integrated in-bed patient scales, and automated exit alarms for intensive care wards.',
    keySpecifications: [
      'Continuous Lateral Rotation Therapy (CLRT) up to 40° for pulmonary drainage',
      'FullChair positioning enables cardiac chair elevation with one touch',
      'Integrated class III medical-grade patient weighing scale system',
      'StayInPlace technology minimizes patient migration down the mattress',
      'Smart bed connectivity: nurse call integration and patient fall detection',
    ],
    complianceStandards: ['MDA Class A Registered', 'CE Certified', 'IEC 60601-2-52', 'ISO 9001'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 3,
    leadTimeWeeks: 2,
    warrantyYears: 3,
    powerRequirements: '220-240V AC, 50Hz with emergency backup battery',
    dimensions: '228 x 103 x 45-88 cm',
    weightKg: 225,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-002',
    name: 'Prime X Series Emergency & Trauma Transport Stretcher',
    modelNumber: 'STRYKER-PRIME-X',
    category: 'NON_MEDICAL',
    subcategory: 'Patient Transfer & Mobility',
    manufacturer: 'Stryker Medical',
    originCountry: 'United States',
    description: 'Heavy-duty 318 kg capacity emergency transfer stretcher with full-length radiolucent sub-deck for whole-body X-ray trauma imaging without requiring patient transfer.',
    keySpecifications: [
      'Full-length dual-cassette radiolucent deck for X-ray & C-arm fluoroscopy',
      'Advanced steering wheel technology reduces start-up push force',
      'Thermoformed base with built-in dual oxygen cylinder storage',
      'Hydraulic dual-side foot pedal elevation and Trendelenburg controls',
      'Integrated foldable IV pole and Glideaway protective side rails',
    ],
    complianceStandards: ['MDA Class A Registered', 'CE Certified', 'ISO 9001'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 1,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    powerRequirements: 'Manual Hydraulic (No electrical power required)',
    dimensions: '213 x 86 x 53-89 cm',
    weightKg: 138,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-003',
    name: 'Avalo Series Emergency Resuscitation Crash Cart',
    modelNumber: 'CAPSA-AVALO-EMG',
    category: 'NON_MEDICAL',
    subcategory: 'Clinical Trolleys & Storage',
    manufacturer: 'Capsa Healthcare',
    originCountry: 'United States',
    description: 'Precision-engineered emergency resuscitation cart with breakaway security seal lock, multi-tiered drawer organization, defibrillator swivel mount, and cardiac CPR backboard.',
    keySpecifications: [
      'High-impact polymer structural body with seamless infection-control corners',
      'Breakaway security tag central locking mechanism for rapid ER access',
      '360° rotating defibrillator tray with safety strapping',
      'Integrated acrylic CPR backboard, oxygen cylinder holder, and IV pole',
      '5 full-extension ball-bearing drawers with customizable sub-dividers',
    ],
    complianceStandards: ['ISO 9001'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 1,
    leadTimeWeeks: 1,
    warrantyYears: 3,
    dimensions: '68 x 98 x 108 cm',
    weightKg: 52,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-004',
    name: 'TSX Series -86°C Ultra-Low Temperature Medical Freezer',
    modelNumber: 'THERMO-TSX-400V',
    category: 'NON_MEDICAL',
    subcategory: 'Cold Chain & Specimen Storage',
    manufacturer: 'Thermo Fisher Scientific',
    originCountry: 'United States',
    description: 'V-drive adaptive compressor ultra-low freezer for clinical vaccine, blood plasma, and biological specimen storage with natural hydrocarbon refrigerants and low energy footprint.',
    keySpecifications: [
      'Temperature range: -50°C to -86°C with microprocessor PID controller',
      'V-drive technology adapts to user access patterns for uniform cooling',
      'Holds up to 400 standard 2-inch cryoboxes (548 Liters internal capacity)',
      'Touchscreen interface with USB temperature logging and remote alarm ports',
      'Whisper-quiet operational noise level (45.5 dBA)',
    ],
    complianceStandards: ['CE Certified', 'ENERGY STAR Certified', 'ISO 13485'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 3,
    warrantyYears: 5,
    powerRequirements: '230V, 50Hz, 8.5 kWh/day',
    dimensions: '198 x 72 x 95 cm',
    weightKg: 310,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-005',
    name: 'Smart-UPS On-Line 10kVA Medical Isolation Power System',
    modelNumber: 'APC-SRT10KXLI-MED',
    category: 'NON_MEDICAL',
    subcategory: 'Facility & Electrical Infrastructure',
    manufacturer: 'Schneider Electric / APC',
    originCountry: 'France',
    description: 'Double-conversion online uninterruptible power supply with medical isolation transformer, galvanic isolation, zero transfer time, and surge protection for sensitive imaging and life support systems.',
    keySpecifications: [
      '10,000 VA / 10,000 Watts pure sine wave online double-conversion power',
      'Built-in medical grade ultra-low leakage current isolation transformer (< 100 µA)',
      'Zero transfer time (0 ms) to battery backup during mains interruption',
      'Hot-swappable user-replaceable battery modules with scalable runtime packs',
      'SNMP network management card for remote facility monitoring',
    ],
    complianceStandards: ['IEC 60601-1-2 Medical EMC', 'CE Certified', 'ISO 9001'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 2,
    warrantyYears: 3,
    powerRequirements: 'Input: 230V / 400V 3-Phase, Output: 230V Single-Phase Pure Sine',
    dimensions: '43.2 x 26.3 x 71.5 cm',
    weightKg: 112,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-006',
    name: 'Coronis Uniti 12MP Diagnostic PACS Medical Display',
    modelNumber: 'BARCO-MDMC-12133',
    category: 'NON_MEDICAL',
    subcategory: 'IT & PACS Workstations',
    manufacturer: 'Barco',
    originCountry: 'Belgium',
    description: '12-Megapixel fusion diagnostic display workstation calibrated for multi-modality PACS reading, mammography tomosynthesis, CT, MRI, and color ultrasound review on a single bezel-free screen.',
    keySpecifications: [
      '33-inch active matrix color IPS-TFT panel with 12MP (4200 x 2800) resolution',
      'OpticalGlass anti-reflective coating with calibrated peak brightness',
      'Continuous automated DICOM Part 14 calibration sensor (I-Guard)',
      'Dual-display color fusion technology for side-by-side greyscale and color reading',
      'Ambient light compensation sensor',
    ],
    complianceStandards: ['MDA Class B Registered', 'CE Certified', 'DICOM Part 14'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 2,
    warrantyYears: 5,
    powerRequirements: '100-240V AC, 50/60Hz, 125W',
    dimensions: '78 x 59 x 29 cm',
    weightKg: 19.5,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-007',
    name: 'Hands-Free Stainless Steel Clinical Biohazard Waste Trolley',
    modelNumber: 'MED-WASTE-SS70',
    category: 'NON_MEDICAL',
    subcategory: 'Sanitation & Waste Disposal',
    manufacturer: 'HealthGrid Clinical Fabrication',
    originCountry: 'Malaysia',
    description: 'Heavy-duty Grade 304 stainless steel foot-pedal operated medical waste disposal trolley designed for clinical waste containment standards in healthcare facilities.',
    keySpecifications: [
      'Full Grade 304 satin-finish stainless steel body resistant to healthcare disinfectants',
      'Hydraulic soft-close damper prevents aerosol dispersion during lid closure',
      'Heavy-duty non-marking antistatic rubber swivel castors with individual brakes',
      'Internal bag retention ring prevents clinical yellow biohazard bag slippage',
      '70 Liters capacity with leak-proof bottom containment reservoir',
    ],
    complianceStandards: ['ISO 9001'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 1,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    dimensions: '45 x 42 x 78 cm',
    weightKg: 14,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-008',
    name: 'Invacare Reliant 450 Heavy-Duty Electric Patient Lift',
    modelNumber: 'INVACARE-R450-LIFT',
    category: 'NON_MEDICAL',
    subcategory: 'Patient Transfer & Mobility',
    manufacturer: 'Invacare',
    originCountry: 'United States',
    description: 'Motorized patient mobile transfer hoist with 204 kg safe working load, ergonomic sling bar, adjustable base width, and emergency manual lowering system for rehabilitation and ward areas.',
    keySpecifications: [
      'Safe working load capacity: 204 kg (450 lbs) with high-strength steel frame',
      'Electric actuator hoist with hand pendant remote control and battery gauge',
      'Foot-pedal operated adjustable base spreads wide around chairs and beds',
      'Padded 6-point spreader bar accommodates standard clinical slings',
      'Emergency manual lowering mechanism for patient safety during power interruption',
    ],
    complianceStandards: ['CE Certified', 'ISO 10535'],
    procurementOptions: ['PURCHASE', 'RENTAL'],
    minRentalPeriodMonths: 3,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    powerRequirements: '24V DC battery pack with off-board charging station',
    dimensions: '122 x 66-104 x 115-185 cm',
    weightKg: 48,
    availability: 'AVAILABLE',
  },
  {
    id: 'EQ-NON-009',
    name: 'Barrier-Free Power Examination Chair & Consultation Table',
    modelNumber: 'MIDMARK-626-PRO',
    category: 'NON_MEDICAL',
    subcategory: 'Ward & Furniture',
    manufacturer: 'Midmark Corporation',
    originCountry: 'United States',
    description: 'Motorized low-height power examination table with heated upholstery, pelvic tilt, stirrups, and digital weight scale for accessible outpatient consultations in healthcare facilities.',
    keySpecifications: [
      'Ultra-low 39 cm entry height allows easy wheelchair-to-table patient transfer',
      'Powered height, backrest, and pelvic tilt controlled via foot and hand switches',
      'Integrated scale system accurately weighs patients directly on the examination table',
      'CleanAssist roller base enables table movement for room sanitation',
      'Hideaway stirrups with lateral and longitudinal angle adjustments',
    ],
    complianceStandards: ['MDA Class A Registered', 'CE Certified'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 6,
    leadTimeWeeks: 3,
    warrantyYears: 3,
    powerRequirements: '220-240V AC, 50Hz, 10A',
    dimensions: '180 x 71 x 39-94 cm',
    weightKg: 180,
    availability: 'UNAVAILABLE',
  },
  {
    id: 'EQ-NON-010',
    name: 'Heavy-Duty Modular Stainless Steel Linen & Dressing Trolley',
    modelNumber: 'HG-TROLLEY-SS3',
    category: 'NON_MEDICAL',
    subcategory: 'Clinical Trolleys & Storage',
    manufacturer: 'HealthGrid Clinical Fabrication',
    originCountry: 'Malaysia',
    description: 'Three-tier dressing and utility trolley with safety guardrails, quiet polyurethane castors, and heavy-gauge stainless steel sound-deadened shelving for clinic wards.',
    keySpecifications: [
      'Constructed from seamless 1.2mm thick Grade 304 stainless steel tubing',
      'Three deep shelves with 3-sided 50mm perimeter safety retaining rails',
      'Under-shelf sound deadening damping material eliminates metallic clatter',
      'Four 100mm swivel polyurethane castors (2 with total-lock foot brakes)',
      'Maximum static load capacity: 150 kg evenly distributed',
    ],
    complianceStandards: ['ISO 9001'],
    procurementOptions: ['PURCHASE'],
    minRentalPeriodMonths: 1,
    leadTimeWeeks: 1,
    warrantyYears: 2,
    dimensions: '90 x 50 x 95 cm',
    weightKg: 24,
    availability: 'AVAILABLE',
  },
];

// Initial mock quotations for demonstration and Super Admin order management
export const mockInitialQuotations: QuotationRequest[] = [
  {
    id: 'RFQ-2026-0001',
    quotationNumber: 'QUO-2026-1048',
    userId: 'u_dr_norhayati',
    userName: 'Dr. Norhayati Ahmad',
    userRole: 'Medical Officer',
    userEmail: 'norhayati.ahmad@moh.gov.my',
    userPhone: '+60 12-384 9201',
    facilityName: 'Klinik Kesihatan Ampang',
    deliveryAddress: 'Jalan Kerja Air Lama, Ampang Jaya, 68000 Ampang, Selangor',
    requiredByDate: '2026-09-15',
    urgency: 'URGENT',
    notes: 'Urgent replacement needed for maternal & neonatal ultrasound and telemetry monitors prior to clinic audit.',
    items: [
      {
        id: 'QI-001',
        equipmentId: 'EQ-MED-002',
        itemName: 'Voluson E10 High-End 4D Obstetric Ultrasound System',
        modelNumber: 'VOLUSON-E10-BT22',
        category: 'MEDICAL',
        subcategory: 'Diagnostic Imaging',
        manufacturer: 'GE HealthCare',
        isCustom: false,
        quantity: 1,
        procurementIntent: 'PURCHASE',
        unitPrice: 285000,
        subtotal: 285000,
      },
      {
        id: 'QI-002',
        equipmentId: 'EQ-MED-003',
        itemName: 'IntelliVue MX450 Compact Multi-Parameter Patient Monitor',
        modelNumber: 'PHILIPS-MX450-CLINICAL',
        category: 'MEDICAL',
        subcategory: 'Patient Monitoring',
        manufacturer: 'Philips Healthcare',
        isCustom: false,
        quantity: 2,
        procurementIntent: 'PURCHASE',
        unitPrice: 24500,
        subtotal: 49000,
      },
    ],
    status: 'QUOTATION_ISSUED',
    createdAt: '2026-08-10T09:30:00.000Z',
    updatedAt: '2026-08-11T14:15:00.000Z',
    validUntil: '2026-09-10',
    subtotalAmount: 334000,
    discountAmount: 16700,
    sstTaxAmount: 19038,
    totalAmount: 336338,
    paymentTerms: '30 Days Net upon MoH Asset Commissioning',
    warrantyTerms: '3 Years Comprehensive Parts & Labour with 24/7 On-Site SLA',
    deliveryLeadTimeWeeks: 3,
    adminRemarks: 'Official MoH vendor package discount applied (5%). Certified MDA Class B compliant with calibration certificates.',
    reviewedByAdminId: 'superadmin_1',
    reviewedByAdminName: 'Super Admin Office — Procurement Division',
    negotiationHistory: [
      {
        id: 'neg-1',
        senderId: 'superadmin_1',
        senderName: 'Super Admin Procurement Office',
        senderRole: 'Super Admin',
        timestamp: '2026-08-11T14:15:00.000Z',
        message: 'Official quotation issued with 5% institutional bulk discount and expedited 3-week delivery SLA.',
        adminRevisedDiscountPercent: 5,
      },
    ],
  },
  {
    id: 'RFQ-2026-0002',
    userId: 'u_farid',
    userName: 'Farid Zakaria',
    userRole: 'Equipment Marketplace',
    userEmail: 'farid.zakaria@healthgrid.internal',
    userPhone: '+60 17-299 4410',
    facilityName: 'Hospital Selayang — Emergency & Trauma Wing',
    deliveryAddress: 'Lebuhraya Selayang-Kepong, 68100 Batu Caves, Selangor',
    requiredByDate: '2026-09-30',
    urgency: 'STANDARD',
    notes: 'Long-term leasing evaluation for mobile digital radiography and ward storage upgrades.',
    items: [
      {
        id: 'QI-003',
        equipmentId: 'EQ-MED-001',
        itemName: 'Mobilett Elara Max Mobile Digital Radiography System',
        modelNumber: 'SIEMENS-ELARA-MAX-2026',
        category: 'MEDICAL',
        subcategory: 'Diagnostic Imaging',
        manufacturer: 'Siemens Healthineers',
        isCustom: false,
        quantity: 1,
        procurementIntent: 'RENTAL',
        rentalDurationMonths: 12,
      },
      {
        id: 'QI-004',
        equipmentId: 'EQ-NON-010',
        itemName: 'Heavy-Duty Modular Stainless Steel Linen & Dressing Trolley',
        modelNumber: 'HG-TROLLEY-SS3',
        category: 'NON_MEDICAL',
        subcategory: 'Clinical Trolleys & Storage',
        manufacturer: 'HealthGrid Clinical Fabrication',
        isCustom: false,
        quantity: 4,
        procurementIntent: 'PURCHASE',
      },
    ],
    status: 'SUBMITTED',
    createdAt: '2026-08-15T11:20:00.000Z',
    updatedAt: '2026-08-15T11:20:00.000Z',
    negotiationHistory: [],
  },
  {
    id: 'RFQ-2026-0003',
    quotationNumber: 'QUO-2026-0922',
    userId: 'u_dr_tan',
    userName: 'Dr. Tan Mei Ling',
    userRole: 'Medical Officer',
    userEmail: 'dr.tan.ml@moh.gov.my',
    userPhone: '+60 13-401 8823',
    facilityName: 'Klinik Kesihatan Cheras',
    deliveryAddress: 'Jalan Cheras, Taman Pertama, 56000 Kuala Lumpur',
    requiredByDate: '2026-09-01',
    urgency: 'CRITICAL',
    notes: 'Emergency resuscitation & patient transport readiness.',
    items: [
      {
        id: 'QI-005',
        equipmentId: 'EQ-MED-004',
        itemName: 'R Series ALS Defibrillator & Clinical Resuscitation Monitor',
        modelNumber: 'ZOLL-R-SERIES-PLUS',
        category: 'MEDICAL',
        subcategory: 'Emergency & Resuscitation',
        manufacturer: 'ZOLL Medical Corporation',
        isCustom: false,
        quantity: 1,
        procurementIntent: 'PURCHASE',
        unitPrice: 48000,
        subtotal: 48000,
      },
    ],
    status: 'ACCEPTED',
    createdAt: '2026-08-01T08:00:00.000Z',
    updatedAt: '2026-08-05T16:00:00.000Z',
    decidedAt: '2026-08-05T16:00:00.000Z',
    userDecisionRemarks: 'Approved and confirmed by Head of Clinical Department for immediate purchase order issuance.',
    validUntil: '2026-08-31',
    subtotalAmount: 48000,
    discountAmount: 2400,
    sstTaxAmount: 2736,
    totalAmount: 48336,
    paymentTerms: '14 Days Net upon delivery & verification',
    warrantyTerms: '5 Years Manufacturer Extended Warranty',
    deliveryLeadTimeWeeks: 1,
    adminRemarks: 'Expedited express shipment allocated.',
    reviewedByAdminId: 'superadmin_1',
    reviewedByAdminName: 'Super Admin Office — Procurement Division',
    negotiationHistory: [],
  },
];

