import { User, Clinic, Patient, Case, Report, PatientRequest, AuditLog, MobilePacsVan, RadioScheduleProfile } from '../types';

export const mockUsers: User[] = [
  {
    id: 'doc-001',
    name: 'Dr. Sarah Chen',
    email: 'sarah.chen@healthgrid.my',
    role: 'Doctor',
    specialty: 'General Practice',
    status: 'active',
    createdAt: '2025-01-15T08:00:00Z',
    shift: 'Morning',
    leaveStatus: 'Active',
  },
  {
    id: 'rad-001',
    name: 'Ahmad Razak',
    email: 'ahmad.razak@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-02-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'CT', 'MRI'],
    mobilePacsAssignment: 'van-001',
    deploymentLocationId: 'clinic-001',
  },
  {
    id: 'rad-002',
    name: 'Lim Mei Ling',
    email: 'meiling.lim@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-03-10T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'MRI', 'Ultrasound'],
    deploymentLocationId: 'clinic-002',
  },
  {
    id: 'rad-003',
    name: 'Kumaran Pillai',
    email: 'kumaran.pillai@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-04-05T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['CT', 'X-Ray'],
    deploymentLocationId: 'clinic-003',
  },
  {
    id: 'rad-004',
    name: 'Farah Hanim',
    email: 'farah.hanim@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-05-15T08:00:00Z',
    shift: 'Morning',
    leaveStatus: 'On Leave',
    supportedModalities: ['MRI', 'CT', 'X-Ray'],
    deploymentLocationId: 'clinic-001',
  },
  {
    id: 'rad-005',
    name: 'Wong Jia Hao',
    email: 'jiahao.wong@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-06-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'Ultrasound', 'CT', 'MRI'],
    deploymentLocationId: 'clinic-002',
  },
  {
    id: 'rad-006',
    name: 'Zainal Abidin',
    email: 'zainal.abidin@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-07-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'CT', 'MRI', 'Ultrasound'],
    deploymentLocationId: 'clinic-004',
  },
  {
    id: 'rad-007',
    name: 'Norhaslina Yusoff',
    email: 'norhaslina.yusoff@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-07-15T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['MRI', 'CT', 'X-Ray'],
    deploymentLocationId: 'clinic-004',
  },
  {
    id: 'rad-008',
    name: 'Syed Farid Hassan',
    email: 'syed.farid@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-08-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'Ultrasound', 'CT'],
    deploymentLocationId: 'clinic-005',
  },
  {
    id: 'rad-009',
    name: 'Tan Li Wen',
    email: 'liwen.tan@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-08-15T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'MRI', 'CT', 'Ultrasound'],
    deploymentLocationId: 'clinic-006',
  },
  {
    id: 'rad-010',
    name: 'Anis Farhanah',
    email: 'anis.farhanah@healthgrid.my',
    role: 'Radiographer',
    status: 'active',
    createdAt: '2025-09-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
    supportedModalities: ['X-Ray', 'CT', 'Ultrasound'],
    deploymentLocationId: 'clinic-007',
  },
  {
    id: 'rologist-001',
    name: 'Dr. Priya Nair',
    email: 'priya.nair@healthgrid.my',
    role: 'Radiologist',
    specialty: 'Diagnostic Radiology',
    status: 'active',
    createdAt: '2025-01-20T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
  },
  {
    id: 'dept-001',
    name: 'Nurul Aisyah',
    email: 'nurul.aisyah@healthgrid.my',
    role: 'Radiology Department',
    status: 'active',
    createdAt: '2025-01-10T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
  },
  {
    id: 'admin-001',
    name: 'Tan Wei Ming',
    email: 'weiming.tan@healthgrid.my',
    role: 'Administrator',
    status: 'active',
    createdAt: '2024-12-01T08:00:00Z',
    shift: 'Day',
    leaveStatus: 'Active',
  },
];

export const mockClinics: Clinic[] = [
  {
    id: 'clinic-001',
    name: 'Klinik Kesihatan Putrajaya',
    address: 'Precinct 9, 62250 Putrajaya, Malaysia',
    latitude: 2.9264,
    longitude: 101.6964,
    phone: '+60 3-8888-1234',
    email: 'kk.putrajaya@healthgrid.my',
    status: 'active',
  },
  {
    id: 'clinic-002',
    name: 'Klinik Kesihatan Cyberjaya',
    address: 'Persiaran Apec, 63000 Cyberjaya, Selangor',
    latitude: 2.9213,
    longitude: 101.6559,
    phone: '+60 3-8888-5678',
    email: 'kk.cyberjaya@healthgrid.my',
    status: 'active',
  },
  {
    id: 'clinic-003',
    name: 'Klinik Kesihatan Bangi',
    address: 'Jalan Reko, 43650 Bandar Baru Bangi, Selangor',
    latitude: 2.9469,
    longitude: 101.7636,
    phone: '+60 3-8888-9012',
    email: 'kk.bangi@healthgrid.my',
    status: 'active',
  },
  {
    id: 'clinic-004',
    name: 'Hospital Tanjong Karang',
    address: 'KM8, Jalan Sungai Terap 5, 45500 Tanjong Karang, Selangor',
    latitude: 3.4242,
    longitude: 101.1824,
    phone: '+60 3-3269-2333',
    email: 'htk@moh.gov.my',
    status: 'active',
  },
  {
    id: 'clinic-005',
    name: 'Klinik Kesihatan Ijok',
    address: 'JKR 1087, Jln 14, Ijok, 45600 Batang Berjuntai, Selangor',
    latitude: 3.3636,
    longitude: 101.3843,
    phone: '+60 3-6075-1133',
    email: 'kk.ijok@moh.gov.my',
    status: 'active',
  },
  {
    id: 'clinic-006',
    name: 'Klinik Kesihatan Bestari Jaya',
    address: '1867, Jln Kampung, Pekan Batang Berjuntai, 45600 Batang Berjuntai, Selangor',
    latitude: 3.3855,
    longitude: 101.4137,
    phone: '+60 3-6075-2211',
    email: 'kk.bestarijaya@moh.gov.my',
    status: 'active',
  },
  {
    id: 'clinic-007',
    name: 'Klinik Kesihatan Bukit Cherakah',
    address: 'Jln Rizab Masjid, Kampung Bukit Cherakah, 45800 Jeram, Selangor',
    latitude: 3.2072,
    longitude: 101.4633,
    phone: '+60 3-6075-3344',
    email: 'kk.bukitcherakah@moh.gov.my',
    status: 'active',
  },
];

export const mockPatients: Patient[] = [
  {
    id: 'patient-001',
    name: 'Mohd Hafiz bin Ibrahim',
    dob: '1985-03-12',
    gender: 'Male',
    phone: '+60 12-345-6789',
    email: 'hafiz.ibrahim@email.com',
    address: '12 Jalan Merdeka, 62000 Putrajaya',
    latitude: 2.9264,
    longitude: 101.6964,
    medicalHistory: ['Hypertension', 'Type 2 Diabetes'],
    nric: '850312-01-5678',
    mrn: 'MRN-2025-0001',
    clinicId: 'clinic-001',
    clinicName: 'Klinik Kesihatan Putrajaya',
  },
  {
    id: 'patient-002',
    name: 'Siti Aminah binti Yusof',
    dob: '1992-07-25',
    gender: 'Female',
    phone: '+60 13-456-7890',
    email: 'siti.aminah@email.com',
    address: '45 Persiaran Multimedia, 63000 Cyberjaya',
    latitude: 2.9213,
    longitude: 101.6559,
    medicalHistory: ['Asthma'],
    nric: '920725-10-4321',
    mrn: 'MRN-2025-0002',
    clinicId: 'clinic-002',
    clinicName: 'Klinik Kesihatan Cyberjaya',
  },
  {
    id: 'patient-003',
    name: 'Raj Kumar a/l Subramaniam',
    dob: '1978-11-03',
    gender: 'Male',
    phone: '+60 14-567-8901',
    email: 'raj.kumar@email.com',
    address: '78 Jalan Reko, 43650 Bangi',
    latitude: 2.9469,
    longitude: 101.7636,
    medicalHistory: ['Chronic Back Pain', 'Previous Spinal Surgery'],
    nric: '781103-14-7890',
    mrn: 'MRN-2025-0003',
    clinicId: 'clinic-003',
    clinicName: 'Klinik Kesihatan Bangi',
  },
  {
    id: 'patient-004',
    name: 'Tan Siew Bee',
    dob: '1990-05-18',
    gender: 'Female',
    phone: '+60 16-789-0123',
    email: 'siewbee.tan@email.com',
    address: '15 Jalan Puchong, 47100 Puchong, Selangor',
    latitude: 3.0004,
    longitude: 101.6168,
    medicalHistory: ['Knee Injury'],
    nric: '900518-10-2345',
    mrn: 'MRN-2025-0004',
    clinicId: 'clinic-002',
    clinicName: 'Klinik Kesihatan Cyberjaya',
  },
  {
    id: 'patient-005',
    name: 'Muhammad Aiman Hakim',
    dob: '1990-01-15',
    gender: 'Male',
    phone: '+60 13-850-1786',
    email: 'aiman.hakim90@gmail.com',
    address: '22, Jalan Makmur, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Lumbar Disc Herniation'],
    nric: '900115-10-5671',
    mrn: 'MRN-2026-0005',
    emergencyContact: 'Fatimah binti Ahmad — Wife — 016-8042960',
  },
  {
    id: 'patient-006',
    name: 'Ahmad Danish Iskandar',
    dob: '1992-06-22',
    gender: 'Male',
    phone: '+60 14-153-2411',
    email: 'danish.iskandar92@gmail.com',
    address: '1, Jalan Ijok Damai, Taman Ijok Damai, 45700 Batang Berjuntai, Selangor',
    medicalHistory: ['Osteoarthritis'],
    nric: '920622-10-4533',
    mrn: 'MRN-2026-0006',
    emergencyContact: 'Noraini binti Hassan — Mother — 018-9118998',
  },
  {
    id: 'patient-007',
    name: 'Muhammad Firdaus Zaki',
    dob: '1991-03-08',
    gender: 'Male',
    phone: '+60 13-580-0855',
    email: 'firdaus.zaki91@gmail.com',
    address: '18, Jalan Makmur, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Suspected Lung Cancer', 'Chronic cough 3 months'],
    nric: '910308-10-7851',
    mrn: 'MRN-2026-0007',
    emergencyContact: 'Zarina binti Othman — Wife — 015-5719407',
  },
  {
    id: 'patient-008',
    name: 'Mohd Haziq Azman',
    dob: '1993-09-14',
    gender: 'Male',
    phone: '+60 14-143-0314',
    email: 'haziq.azman93@gmail.com',
    address: '32, Jalan Desa Mawar 2/3, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Brain Tumor Investigation', 'Persistent headaches'],
    nric: '930914-10-2317',
    mrn: 'MRN-2026-0008',
    emergencyContact: 'Azman bin Yusof — Father — 019-3661744',
  },
  {
    id: 'patient-009',
    name: 'Muhammad Arif Hakimi',
    dob: '1994-11-25',
    gender: 'Male',
    phone: '+60 10-252-5650',
    email: 'arif.hakimi94@gmail.com',
    address: '6, Jln Desa Bestari 23, Desa Bestari, 43900 Sepang, Selangor',
    medicalHistory: ['Wrist Fracture'],
    nric: '941125-10-6591',
    mrn: 'MRN-2026-0009',
    emergencyContact: 'Hakimi bin Razak — Father — 017-1789941',
  },
  {
    id: 'patient-010',
    name: 'Amirul Hafiz Roslan',
    dob: '1992-08-17',
    gender: 'Male',
    phone: '+60 12-452-5980',
    email: 'amirul.roslan92@gmail.com',
    address: '3, Jalan Desa Mawar 2/1, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Stroke Assessment', 'Hypertension'],
    nric: '920817-10-3485',
    mrn: 'MRN-2026-0010',
    emergencyContact: 'Roslan bin Ahmad — Father — 012-9870765',
  },
  {
    id: 'patient-011',
    name: 'Muhammad Syahmi Faiz',
    dob: '1995-04-09',
    gender: 'Male',
    phone: '+60 19-529-2412',
    email: 'syahmi.faiz95@gmail.com',
    address: '38, Jalan Desa Mawar 2/3, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Knee Ligament Injury', 'Sports injury'],
    nric: '950409-10-7213',
    mrn: 'MRN-2026-0011',
    emergencyContact: 'Faiz bin Kamal — Father — 019-2271907',
  },
  {
    id: 'patient-012',
    name: 'Khairul Anuar Ismail',
    dob: '1991-12-03',
    gender: 'Male',
    phone: '+60 11-398-1250',
    email: 'khairul.ismail91@gmail.com',
    address: '149, Jalan Desa Mahang 7, Kampung Parit Mahang, 45800 Jeram, Selangor',
    medicalHistory: ['Tuberculosis Screening', 'Night sweats', 'Weight loss'],
    nric: '911203-10-4589',
    mrn: 'MRN-2026-0012',
    emergencyContact: 'Ismail bin Osman — Father — 016-1639846',
  },
  {
    id: 'patient-013',
    name: 'Muhammad Aqil Danish',
    dob: '1994-02-20',
    gender: 'Male',
    phone: '+60 18-970-3396',
    email: 'aqil.danish94@gmail.com',
    address: '20, Jalan Desa Mawar 1/1, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Head Trauma', 'Post-accident follow-up'],
    nric: '940220-10-8673',
    mrn: 'MRN-2026-0013',
    emergencyContact: 'Rohani binti Ismail — Mother — 017-3425661',
  },
  {
    id: 'patient-014',
    name: 'Mohamad Izzuddin Hakim',
    dob: '1993-07-11',
    gender: 'Male',
    phone: '+60 10-761-4878',
    email: 'izzuddin.hakim93@gmail.com',
    address: '14, Jalan Desa Mawar 3/7, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Kidney Stone', 'Recurrent flank pain'],
    nric: '930711-10-5241',
    mrn: 'MRN-2026-0014',
    emergencyContact: 'Hakim bin Sulaiman — Father — 011-3558951',
  },
  {
    id: 'patient-015',
    name: 'Nurul Izzati Rahman',
    dob: '1995-10-30',
    gender: 'Female',
    phone: '+60 12-987-4457',
    email: 'nurul.izzati95@gmail.com',
    address: '1, Jalan BSC 3A/9, 48020, Selangor',
    medicalHistory: ['Ankle Sprain'],
    nric: '951030-10-6482',
    mrn: 'MRN-2026-0015',
    emergencyContact: 'Rahman bin Yusof — Father — 010-6414400',
  },
  {
    id: 'patient-016',
    name: 'Siti Aisyah Hamdan',
    dob: '1998-01-28',
    gender: 'Female',
    phone: '+60 15-377-0833',
    email: 'aisyah.hamdan98@gmail.com',
    address: '4, Jalan Desa Mawar 3/13, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Pulmonary Embolism', 'Chest pain', 'Shortness of breath'],
    nric: '980128-10-4356',
    mrn: 'MRN-2026-0016',
    emergencyContact: 'Hamdan bin Ali — Father — 018-4765073',
  },
  {
    id: 'patient-017',
    name: 'Nur Amira Sofea',
    dob: '1997-05-12',
    gender: 'Female',
    phone: '+60 18-117-1596',
    email: 'amira.sofea97@gmail.com',
    address: '2, Jalan Desa Mawar 2/15, Taman Desa Mawar, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Abdominal Pain', 'Loss of appetite'],
    nric: '970512-10-2784',
    mrn: 'MRN-2026-0017',
    emergencyContact: 'Sofea binti Kamal — Mother — 015-4193453',
  },
  {
    id: 'patient-018',
    name: 'Nur Syafiqah Nabila',
    dob: '1999-08-04',
    gender: 'Female',
    phone: '+60 15-960-7378',
    email: 'syafiqah.nabila99@gmail.com',
    address: '69, Jalan Permai 1, Desa Salak Permai, 43900 Sepang, Selangor',
    medicalHistory: ['Pneumonia', 'Visual Impairment'],
    nric: '990804-10-3568',
    mrn: 'MRN-2026-0018',
    emergencyContact: 'Nabila binti Hassan — Mother — 018-3282522',
  },
  {
    id: 'patient-019',
    name: 'Siti Nur Alya',
    dob: '1996-12-19',
    gender: 'Female',
    phone: '+60 16-909-2640',
    email: 'sitinuralya96@gmail.com',
    address: '7, Jalan Nilam 7, Taman Nilam, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Multiple Sclerosis', 'Progressive weakness'],
    nric: '961219-10-8924',
    mrn: 'MRN-2026-0019',
    emergencyContact: 'Alya binti Zainol — Mother — 012-1736852',
  },
  {
    id: 'patient-020',
    name: 'Nurin Balqis',
    dob: '1998-03-16',
    gender: 'Female',
    phone: '+60 14-669-4027',
    email: 'nurin.balqis98@gmail.com',
    address: '13, Jalan 5, Taman Padi Emas, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Chronic Back Pain', 'Hearing Impairment'],
    nric: '980316-10-5142',
    mrn: 'MRN-2026-0020',
    emergencyContact: 'Balqis binti Razak — Mother — 018-4020773',
  },
  {
    id: 'patient-021',
    name: 'Aina Farhana Kamal',
    dob: '1997-09-07',
    gender: 'Female',
    phone: '+60 18-763-7889',
    email: 'aina.kamal97@gmail.com',
    address: '3, Jalan Ria Mas 3, Taman Ria Mas, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Liver Lesion Assessment', 'Elevated liver enzymes'],
    nric: '970907-10-6348',
    mrn: 'MRN-2026-0021',
    emergencyContact: 'Kamal bin Ismail — Father — 013-8715690',
  },
  {
    id: 'patient-022',
    name: 'Nur Athirah Zulaikha',
    dob: '1999-06-23',
    gender: 'Female',
    phone: '+60 19-103-8924',
    email: 'athirah.zulaikha99@gmail.com',
    address: '9, Jalan Ria Mas 3, Taman Ria Mas, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Stroke Follow-Up', 'Left-sided weakness'],
    nric: '990623-10-7582',
    mrn: 'MRN-2026-0022',
    emergencyContact: 'Zulaikha binti Osman — Mother — 010-5172349',
  },
  {
    id: 'patient-023',
    name: 'Puteri Nabilah Ahmad',
    dob: '1996-04-15',
    gender: 'Female',
    phone: '+60 19-673-6803',
    email: 'puteri.nabilah96@gmail.com',
    address: '10, Jalan Nilam 6, Kampung Sungai Terap, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Sinus Disease', 'Physical Disability', 'Chronic nasal congestion'],
    nric: '960415-10-2946',
    mrn: 'MRN-2026-0023',
    emergencyContact: 'Ahmad bin Yusuf — Father — 013-5670244',
  },
  {
    id: 'patient-024',
    name: 'Nur Sabrina Syazana',
    dob: '1998-11-02',
    gender: 'Female',
    phone: '+60 19-673-5432',
    email: 'sabrina.syazana98@gmail.com',
    address: '11, Jalan Nilam 6, Kampung Sungai Terap, 45500 Tanjong Karang, Selangor',
    medicalHistory: ['Cervical Disc Compression', 'Neck pain with radiating numbness'],
    nric: '981102-10-4128',
    mrn: 'MRN-2026-0024',
    emergencyContact: 'Syazana binti Kamal — Mother — 013-5670234',
  },
];

export const mockCases: Case[] = [
  {
    id: 'case-001',
    caseNumber: 'HG-2026-0001',
    patientId: 'patient-001',
    patientName: 'Mohd Hafiz bin Ibrahim',
    doctorId: 'doc-001',
    doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001',
    radiographerName: 'Ahmad Razak',
    radiologistId: 'rologist-001',
    radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-001',
    clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'Chest X-Ray',
    notes: 'Persistent cough for 3 weeks. Rule out pneumonia or TB.',
    status: 'FINALIZED',
    createdAt: '2026-06-01T09:00:00Z',
    scheduledAt: '2026-06-03T10:00:00Z',
    scannedAt: '2026-06-03T10:30:00Z',
    reportedAt: '2026-06-03T14:00:00Z',
    finalizedAt: '2026-06-03T15:00:00Z',
    images: [],
  },
  {
    id: 'case-002',
    caseNumber: 'HG-2026-0002',
    patientId: 'patient-002',
    patientName: 'Siti Aminah binti Yusof',
    doctorId: 'doc-001',
    doctorName: 'Dr. Sarah Chen',
    clinicId: 'clinic-002',
    clinicName: 'Klinik Kesihatan Cyberjaya',
    scanType: 'Brain MRI',
    notes: 'Recurrent migraines with visual aura. MRI to rule out intracranial pathology.',
    status: 'CREATED',
    createdAt: '2026-07-10T09:00:00Z',
  },
  {
    id: 'case-003',
    caseNumber: 'HG-2026-0003',
    patientId: 'patient-003',
    patientName: 'Raj Kumar a/l Subramaniam',
    doctorId: 'doc-001',
    doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001',
    radiographerName: 'Ahmad Razak',
    clinicId: 'clinic-003',
    clinicName: 'Klinik Kesihatan Bangi',
    scanType: 'Lumbar Spine CT',
    notes: 'Post-surgical follow up. Evaluate hardware positioning and healing.',
    status: 'SCANNED',
    createdAt: '2026-07-08T09:00:00Z',
    scheduledAt: '2026-07-12T11:00:00Z',
    scannedAt: '2026-07-12T11:45:00Z',
    images: [],
  },
  {
    id: 'case-004',
    caseNumber: 'HG-2026-0004',
    patientId: 'patient-001',
    patientName: 'Mohd Hafiz bin Ibrahim',
    doctorId: 'doc-001',
    doctorName: 'Dr. Sarah Chen',
    clinicId: 'clinic-001',
    clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'Abdominal Ultrasound',
    notes: 'Epigastric pain, elevated liver enzymes. Evaluate hepatobiliary system.',
    status: 'SCHEDULED',
    createdAt: '2026-07-14T09:00:00Z',
    scheduledAt: '2026-07-16T09:00:00Z',
    radiographerId: 'rad-001',
    radiographerName: 'Ahmad Razak',
  },
  {
    id: 'case-005',
    caseNumber: 'HG-2026-0005',
    patientId: 'patient-004',
    patientName: 'Tan Siew Bee',
    doctorId: 'doc-001',
    doctorName: 'Dr. Sarah Chen',
    clinicId: 'clinic-002',
    clinicName: 'Klinik Kesihatan Cyberjaya',
    scanType: 'Knee MRI',
    notes: 'ACL injury suspected after sports accident. Evaluate ligament integrity.',
    status: 'CREATED',
    createdAt: '2026-07-15T08:00:00Z',
  },
  {
    id: 'case-006', caseNumber: 'XR2026030001', patientId: 'patient-005', patientName: 'Muhammad Aiman Hakim',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Lumbar Spine',
    notes: 'Lumbar Disc Herniation. Moderate severity. Evaluate disc protrusion and nerve compression.', status: 'CREATED', createdAt: '2026-05-21T15:30:00Z',
  },
  {
    id: 'case-007', caseNumber: 'XR2026030002', patientId: 'patient-006', patientName: 'Ahmad Danish Iskandar',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Knee X-Ray',
    notes: 'Osteoarthritis. Low severity. Evaluate joint space narrowing and osteophyte formation.', status: 'CREATED', createdAt: '2026-05-22T14:00:00Z',
  },
  {
    id: 'case-008', caseNumber: 'XR2026030003', patientId: 'patient-007', patientName: 'Muhammad Firdaus Zaki',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Thorax',
    notes: 'Suspected Lung Cancer. High severity. Chronic cough 3 months, weight loss, hemoptysis.', status: 'CREATED', createdAt: '2026-05-23T15:00:00Z',
  },
  {
    id: 'case-009', caseNumber: 'XR2026030004', patientId: 'patient-008', patientName: 'Mohd Haziq Azman',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Brain',
    notes: 'Brain Tumor Investigation. High severity. Persistent headaches, visual disturbance.', status: 'CREATED', createdAt: '2026-05-24T10:15:00Z',
  },
  {
    id: 'case-010', caseNumber: 'XR2026030005', patientId: 'patient-009', patientName: 'Muhammad Arif Hakimi',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Wrist X-Ray',
    notes: 'Wrist Fracture. Moderate severity. Fall on outstretched hand, swelling and tenderness.', status: 'CREATED', createdAt: '2026-05-25T13:45:00Z',
  },
  {
    id: 'case-011', caseNumber: 'XR2026030006', patientId: 'patient-010', patientName: 'Amirul Hafiz Roslan',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Brain',
    notes: 'Stroke Assessment. High severity. Sudden onset left-sided weakness and speech difficulty.', status: 'CREATED', createdAt: '2026-05-26T15:00:00Z',
  },
  {
    id: 'case-012', caseNumber: 'XR2026030007', patientId: 'patient-011', patientName: 'Muhammad Syahmi Faiz',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Knee MRI',
    notes: 'Knee Ligament Injury. Moderate severity. Sports injury, instability on examination.', status: 'CREATED', createdAt: '2026-05-27T11:45:00Z',
  },
  {
    id: 'case-013', caseNumber: 'XR2026030008', patientId: 'patient-012', patientName: 'Khairul Anuar Ismail',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Chest X-Ray',
    notes: 'Tuberculosis Screening. High severity. Night sweats, weight loss, productive cough.', status: 'CREATED', createdAt: '2026-05-28T14:45:00Z',
  },
  {
    id: 'case-014', caseNumber: 'XR2026030009', patientId: 'patient-013', patientName: 'Muhammad Aqil Danish',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Brain',
    notes: 'Head Trauma. High severity. Post-accident, GCS 14, rule out intracranial hemorrhage.', status: 'CREATED', createdAt: '2026-05-29T16:45:00Z',
  },
  {
    id: 'case-015', caseNumber: 'XR2026030010', patientId: 'patient-014', patientName: 'Mohamad Izzuddin Hakim',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Abdomen',
    notes: 'Kidney Stone. Moderate severity. Recurrent flank pain, hematuria.', status: 'CREATED', createdAt: '2026-05-30T14:15:00Z',
  },
  {
    id: 'case-016', caseNumber: 'XR2026030011', patientId: 'patient-015', patientName: 'Nurul Izzati Rahman',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Ankle X-Ray',
    notes: 'Ankle Sprain Assessment. Low severity. Inversion injury during sports.', status: 'CREATED', createdAt: '2026-05-31T15:45:00Z',
  },
  {
    id: 'case-017', caseNumber: 'XR2026030012', patientId: 'patient-016', patientName: 'Siti Aisyah Hamdan',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Pulmonary Angiography',
    notes: 'Pulmonary Embolism. High severity. Acute chest pain, tachycardia, elevated D-dimer.', status: 'CREATED', createdAt: '2026-06-01T09:30:00Z',
  },
  {
    id: 'case-018', caseNumber: 'XR2026030013', patientId: 'patient-017', patientName: 'Nur Amira Sofea',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Abdomen',
    notes: 'Abdominal Pain Investigation. Moderate severity. Periumbilical pain, nausea.', status: 'CREATED', createdAt: '2026-06-02T10:30:00Z',
  },
  {
    id: 'case-019', caseNumber: 'XR2026030014', patientId: 'patient-018', patientName: 'Nur Syafiqah Nabila',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'Chest X-Ray',
    notes: 'Pneumonia. Moderate severity. Productive cough, fever, visually impaired patient.', status: 'CREATED', createdAt: '2026-06-03T10:15:00Z',
  },
  {
    id: 'case-020', caseNumber: 'XR2026030015', patientId: 'patient-019', patientName: 'Siti Nur Alya',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Brain',
    notes: 'Multiple Sclerosis. High severity. Progressive weakness, optic neuritis.', status: 'CREATED', createdAt: '2026-06-04T14:00:00Z',
  },
  {
    id: 'case-021', caseNumber: 'XR2026030016', patientId: 'patient-020', patientName: 'Nurin Balqis',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Lumbar Spine',
    notes: 'Chronic Back Pain. Low severity. Hearing impaired patient, conservative treatment failure.', status: 'CREATED', createdAt: '2026-06-05T11:45:00Z',
  },
  {
    id: 'case-022', caseNumber: 'XR2026030017', patientId: 'patient-021', patientName: 'Aina Farhana Kamal',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Abdomen',
    notes: 'Liver Lesion Assessment. High severity. Elevated AFP, hepatomegaly.', status: 'CREATED', createdAt: '2026-06-06T10:45:00Z',
  },
  {
    id: 'case-023', caseNumber: 'XR2026030018', patientId: 'patient-022', patientName: 'Nur Athirah Zulaikha',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Brain',
    notes: 'Stroke Follow-Up. Moderate severity. Previous ischaemic stroke, new symptoms.', status: 'CREATED', createdAt: '2026-06-07T10:45:00Z',
  },
  {
    id: 'case-024', caseNumber: 'XR2026030019', patientId: 'patient-023', patientName: 'Puteri Nabilah Ahmad',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'CT Paranasal Sinus',
    notes: 'Sinus Disease. Low severity. Chronic nasal congestion, physically disabled patient.', status: 'CREATED', createdAt: '2026-06-08T10:30:00Z',
  },
  {
    id: 'case-025', caseNumber: 'XR2026030020', patientId: 'patient-024', patientName: 'Nur Sabrina Syazana',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen', scanType: 'MRI Cervical Spine',
    notes: 'Cervical Disc Compression. Moderate severity. Neck pain with radiating numbness to arms.', status: 'CREATED', createdAt: '2026-06-09T10:00:00Z',
  },
];

// ==================== DEMO CASES (from sample radiology report xlsx) ====================
// These 9 FINALIZED cases correspond 1-to-1 with the 9 rows in the sample report spreadsheet.
export const mockDemoCases: Case[] = [
  {
    id: 'demo-case-001', caseNumber: 'HG-DEMO-0001',
    patientId: 'patient-017', patientName: 'Nur Amira Sofea',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001', radiographerName: 'Ahmad Razak',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-001', clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'CT Abdomen & Pelvis', disease: 'Abdominal Pain Investigation',
    bodyRegion: 'Abdomen', severity: 'Moderate',
    notes: 'Periumbilical pain, nausea. CT abdomen to investigate abdominal pain.',
    status: 'FINALIZED',
    createdAt: '2026-06-10T08:00:00Z', scheduledAt: '2026-06-11T09:00:00Z',
    scannedAt: '2026-06-11T09:30:00Z', reportedAt: '2026-06-11T13:00:00Z',
    finalizedAt: '2026-06-11T14:00:00Z', images: [],
  },
  {
    id: 'demo-case-002', caseNumber: 'HG-DEMO-0002',
    patientId: 'patient-021', patientName: 'Aina Farhana Kamal',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-002', radiographerName: 'Lim Mei Ling',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-002', clinicName: 'Klinik Kesihatan Cyberjaya',
    scanType: 'CT Abdomen', disease: 'Liver Lesion Assessment',
    bodyRegion: 'Abdomen', severity: 'Severe',
    notes: 'Elevated AFP, hepatomegaly. CT to assess left hepatic lobe lesion.',
    status: 'FINALIZED',
    createdAt: '2026-06-12T08:00:00Z', scheduledAt: '2026-06-13T10:00:00Z',
    scannedAt: '2026-06-13T10:30:00Z', reportedAt: '2026-06-13T14:00:00Z',
    finalizedAt: '2026-06-13T15:00:00Z', images: [],
  },
  {
    id: 'demo-case-003', caseNumber: 'HG-DEMO-0003',
    patientId: 'patient-012', patientName: 'Khairul Anuar Ismail',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-003', radiographerName: 'Kumaran Pillai',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-003', clinicName: 'Klinik Kesihatan Bangi',
    scanType: 'X-Ray Chest', disease: 'Rib Fracture (Blunt Trauma)',
    bodyRegion: 'Chest', severity: 'Severe',
    notes: 'Blunt chest trauma. X-Ray chest to assess for rib fractures and pneumothorax.',
    status: 'FINALIZED',
    createdAt: '2026-06-14T08:00:00Z', scheduledAt: '2026-06-14T11:00:00Z',
    scannedAt: '2026-06-14T11:30:00Z', reportedAt: '2026-06-14T14:00:00Z',
    finalizedAt: '2026-06-14T15:00:00Z', images: [],
  },
  {
    id: 'demo-case-004', caseNumber: 'HG-DEMO-0004',
    patientId: 'patient-022', patientName: 'Nur Athirah Zulaikha',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001', radiographerName: 'Ahmad Razak',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-001', clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'CT Head/Brain', disease: 'Stroke Follow-Up',
    bodyRegion: 'Head', severity: 'Critical',
    notes: 'Previous ischaemic stroke, new left-sided weakness. CT brain for stroke follow-up.',
    status: 'FINALIZED',
    createdAt: '2026-06-15T08:00:00Z', scheduledAt: '2026-06-15T09:00:00Z',
    scannedAt: '2026-06-15T09:30:00Z', reportedAt: '2026-06-15T13:00:00Z',
    finalizedAt: '2026-06-15T14:00:00Z', images: [],
  },
  {
    id: 'demo-case-005', caseNumber: 'HG-DEMO-0005',
    patientId: 'patient-023', patientName: 'Puteri Nabilah Ahmad',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-002', radiographerName: 'Lim Mei Ling',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-002', clinicName: 'Klinik Kesihatan Cyberjaya',
    scanType: 'CT Paranasal Sinus', disease: 'Sinus Disease',
    bodyRegion: 'Head', severity: 'Mild',
    notes: 'Chronic nasal congestion. CT paranasal sinus to assess sinus disease.',
    status: 'FINALIZED',
    createdAt: '2026-06-16T08:00:00Z', scheduledAt: '2026-06-17T10:00:00Z',
    scannedAt: '2026-06-17T10:30:00Z', reportedAt: '2026-06-17T13:30:00Z',
    finalizedAt: '2026-06-17T14:30:00Z', images: [],
  },
  {
    id: 'demo-case-006', caseNumber: 'HG-DEMO-0006',
    patientId: 'patient-001', patientName: 'Mohd Hafiz bin Ibrahim',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-003', radiographerName: 'Kumaran Pillai',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-003', clinicName: 'Klinik Kesihatan Bangi',
    scanType: 'X-Ray Spine', disease: 'Traumatic Spine Injury',
    bodyRegion: 'Cervical Spine', severity: 'Severe',
    notes: 'Post-trauma cervical spine assessment. Rule out fracture or subluxation.',
    status: 'FINALIZED',
    createdAt: '2026-06-18T08:00:00Z', scheduledAt: '2026-06-18T11:00:00Z',
    scannedAt: '2026-06-18T11:30:00Z', reportedAt: '2026-06-18T14:00:00Z',
    finalizedAt: '2026-06-18T15:00:00Z', images: [],
  },
  {
    id: 'demo-case-007', caseNumber: 'HG-DEMO-0007',
    patientId: 'patient-024', patientName: 'Nur Sabrina Syazana',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001', radiographerName: 'Ahmad Razak',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-001', clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'MRI Spine', disease: 'Cervical Disc Compression',
    bodyRegion: 'Cervical Spine', severity: 'Critical',
    notes: 'Neck pain with radiating numbness. MRI cervical spine for disc compression.',
    status: 'FINALIZED',
    createdAt: '2026-06-19T08:00:00Z', scheduledAt: '2026-06-20T09:00:00Z',
    scannedAt: '2026-06-20T09:30:00Z', reportedAt: '2026-06-20T13:00:00Z',
    finalizedAt: '2026-06-20T14:00:00Z', images: [],
  },
  {
    id: 'demo-case-008', caseNumber: 'HG-DEMO-0008',
    patientId: 'patient-003', patientName: 'Raj Kumar a/l Subramaniam',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-003', radiographerName: 'Kumaran Pillai',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-003', clinicName: 'Klinik Kesihatan Bangi',
    scanType: 'X-Ray Neck', disease: 'Foreign Body (ENT) Evaluation',
    bodyRegion: 'Cervical Spine', severity: 'Mild',
    notes: 'ENT foreign body evaluation. X-Ray neck to assess soft tissue and bony structures.',
    status: 'FINALIZED',
    createdAt: '2026-06-21T08:00:00Z', scheduledAt: '2026-06-21T10:00:00Z',
    scannedAt: '2026-06-21T10:30:00Z', reportedAt: '2026-06-21T13:00:00Z',
    finalizedAt: '2026-06-21T14:00:00Z', images: [],
  },
  {
    id: 'demo-case-009', caseNumber: 'HG-DEMO-0009',
    patientId: 'patient-005', patientName: 'Muhammad Aiman Hakim',
    doctorId: 'doc-001', doctorName: 'Dr. Sarah Chen',
    radiographerId: 'rad-001', radiographerName: 'Ahmad Razak',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    clinicId: 'clinic-001', clinicName: 'Klinik Kesihatan Putrajaya',
    scanType: 'MRI Spine', disease: 'Degenerative Spine Disease (Spondylosis)',
    bodyRegion: 'Cervical Spine', severity: 'Critical',
    notes: 'Progressive neck pain with myelopathy signs. MRI cervical spine for spondylosis evaluation.',
    status: 'FINALIZED',
    createdAt: '2026-06-22T08:00:00Z', scheduledAt: '2026-06-23T09:00:00Z',
    scannedAt: '2026-06-23T09:30:00Z', reportedAt: '2026-06-23T13:00:00Z',
    finalizedAt: '2026-06-23T14:00:00Z', images: [],
  },
];

// Merge demo cases into main cases array at module init time
mockDemoCases.forEach((dc) => {
  if (!mockCases.find((c) => c.id === dc.id)) mockCases.push(dc);
});

export const mockReports: Report[] = [
  {
    id: 'report-001',
    caseId: 'case-001',
    caseNumber: 'HG-2026-0001',
    patientName: 'Mohd Hafiz bin Ibrahim',
    radiologistId: 'rologist-001',
    radiologistName: 'Dr. Priya Nair',
    findings: 'PA and lateral chest radiographs were obtained. The cardiac silhouette is within normal limits. The lungs are clear bilaterally without focal consolidation, effusion, or pneumothorax. The mediastinal contours are unremarkable. No osseous abnormalities identified.',
    impression: 'Normal chest radiograph. No evidence of pneumonia, tuberculosis, or other acute cardiopulmonary process.',
    suggestions: 'If symptoms persist, consider sputum culture or high-resolution CT for further evaluation.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-03T14:00:00Z',
    signedAt: '2026-06-03T15:00:00Z',
  },
  // ===== 9 DEMO REPORTS from sample radiology report xlsx =====
  {
    id: 'report-demo-001',
    caseId: 'demo-case-001', caseNumber: 'HG-DEMO-0001', patientName: 'Nur Amira Sofea',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Liver, spleen, and urinary bladder normal in size and appearance. Visualized small and large bowel loops show normal wall thickness and contain oral contrast. No hydronephrosis, perinephric fat stranding, pneumoperitoneum, or pelvic free fluid.\n\nAbnormalities:\n• Retroperitoneum at L3-L4 level — fusion of lower poles of both kidneys across midline, forming a horseshoe configuration with anteriorly rotated renal pelvises. Connecting parenchymal bridge (isthmus) ~2.0 cm in AP thickness. Homogeneous contrast enhancement matching normal renal tissue.\n• Distal abdominal aorta: calcified atheromatous plaques (non-stenotic).',
    impression: 'Most likely: Horseshoe kidney — ICD-11: GB90.Y (congenital fusion anomaly of lower renal poles). Incidental calcified atheromatous plaques at aortic bifurcation.',
    suggestions: 'No immediate intervention required. Routine clinical surveillance and monitoring of renal function. CT urography or renal ultrasound if symptoms of obstruction, infection, or urolithiasis develop.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-11T13:00:00Z', signedAt: '2026-06-11T14:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-002',
    caseId: 'demo-case-002', caseNumber: 'HG-DEMO-0002', patientName: 'Aina Farhana Kamal',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Right hepatic lobe, spleen, and visualized stomach normal in configuration. Abdominal aorta and IVC patent. No intrahepatic biliary ductal dilatation, portal vein thrombosis, ascites, or secondary focal lesions.\n\nAbnormality — Left hepatic lobe (Segment II/III):\n• Size: ~8.5 × 8.0 × 7.8 cm\n• Morphology: Large, well-demarcated, lobulated hypodense mass\n• Enhancement: Peripheral nodular discontinuous enhancement on arterial phase with progressive centripetal fill-in on portal venous phase, leaving a central non-enhancing cleft.',
    impression: 'Most likely: Giant cavernous hemangioma — ICD-11: 2E81.0. Pathognomonic peripheral nodular discontinuous enhancement with centripetal fill-in. Intrahepatic cholangiocarcinoma, hypervascular metastasis, and HCC considered less likely.',
    suggestions: 'No immediate intervention required (absence of acute symptoms). Surveillance imaging in 6–12 months to confirm stability. MRI abdomen with contrast for definitive characterisation if surgical intervention planned.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-13T14:00:00Z', signedAt: '2026-06-13T15:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-003',
    caseId: 'demo-case-003', caseNumber: 'HG-DEMO-0003', patientName: 'Khairul Anuar Ismail',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Right lung clear. Bony thoracic cage intact on right. Trachea midline. Cardiomediastinal contour within normal limits. No right-sided pneumothorax, effusion, or consolidation.\n\nAbnormalities — Left hemithorax:\n• Left pleural space: visceral pleural line visible with absence of peripheral lung markings, consistent with pneumothorax. Apical-to-cupola distance ~2.5 cm; lateral pleural separation ~2.0 cm.\n• Left chest tube in situ with tip in left upper hemithorax.\n• Mild left chest wall subcutaneous emphysema.',
    impression: 'Most likely: Left-sided pneumothorax — ICD-11: CB23. Left subcutaneous emphysema — ICD-11: NE81.2 secondary to chest tube insertion. Persistent air leak cannot be excluded.',
    suggestions: 'Monitor clinical status and chest tube drainage output. Repeat chest radiograph post-clamping or if clinical status deteriorates. Chest CT if pneumothorax fails to resolve or tube malposition suspected. Confirm chest tube securement.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-14T14:00:00Z', signedAt: '2026-06-14T15:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-004',
    caseId: 'demo-case-004', caseNumber: 'HG-DEMO-0004', patientName: 'Nur Athirah Zulaikha',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Right cerebral hemisphere with preserved gray-white matter differentiation. Ventricles symmetric with mild compression of left lateral ventricle. Brainstem and cerebellum normal. No midline shift or large extra-axial fluid collections.\n\nAbnormalities — Left temporal and parietal lobes including left insular ribbon:\n• Area ~6.5 × 4.0 cm axially: ill-defined hypodensity with loss of gray-white junction and cortical swelling/sulcal effacement.\n• Linear hyperdensities along sulci of left posterior temporal lobe (~60 HU) — consistent with localised subarachnoid haemorrhage or petechial haemorrhagic transformation.',
    impression: 'Most likely: Acute ischaemic infarction in left MCA territory with petechial haemorrhagic transformation — ICD-11: 8B11.5. Cortical subarachnoid haemorrhage secondary to ischaemia considered.',
    suggestions: 'Immediate neurology consult / stroke team activation. CT head without contrast in 24 hours or with any neurological change. CT angiogram of head and neck to evaluate vascular patency.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-15T13:00:00Z', signedAt: '2026-06-15T14:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-005',
    caseId: 'demo-case-005', caseNumber: 'HG-DEMO-0005', patientName: 'Puteri Nabilah Ahmad',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Right orbit, right maxillary sinus, ethmoid air cells, and nasal cavity within normal limits. Both globes intact and symmetric. No fracture of right orbital floor or medial wall. No retrobulbar haematoma or ZMC fracture.\n\nAbnormality — Left orbital floor:\n• Bony defect ~1.2 cm mediolateral dimension with disrupted and depressed fracture.\n• Inferior herniation of orbital fat and potentially the inferior rectus muscle into superior left maxillary sinus (blowout fracture).',
    impression: 'Most likely: Left orbital floor blowout fracture — ICD-11: NC12.0 with herniation of orbital contents, suspicious for inferior rectus muscle entrapment.',
    suggestions: 'Ophthalmology consultation for formal eye examination including assessment for diplopia, EOM restriction, and globe integrity. Avoid nose blowing. Surgical orbital floor reconstruction if clinical entrapment, persistent diplopia, or enophthalmos >2 mm confirmed.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-17T13:30:00Z', signedAt: '2026-06-17T14:30:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-006',
    caseId: 'demo-case-006', caseNumber: 'HG-DEMO-0006', patientName: 'Mohd Hafiz bin Ibrahim',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Cervical vertebral body heights maintained. Atlantoaxial alignment normal with normal atlantodental interval. Spinolaminar and posterior vertebral lines intact. No prevertebral soft tissue swelling.\n\nFindings:\n• Tracheostomy tube in situ passing through anterior soft tissues into trachea — radiopaque, satisfactory position with tip in mid-trachea.\n• Mild anterior osteophyte formation and mild disc space narrowing at C5-C6 and C6-C7 levels.\n• Two circular metallic structures (~1.2 cm each) overlying lower neck — consistent with external ECG electrodes.',
    impression: 'Tracheostomy tube in situ — ICD-11: QB3Y. Mild cervical spondylosis at C5-C6 and C6-C7 — ICD-11: FA80.y. External metallic artefacts (ECG lead snaps). No acute traumatic cervical spine fracture or subluxation.',
    suggestions: 'No immediate action required. Clinical monitoring of tracheostomy site and airway patency. CT cervical spine if high clinical suspicion of occult trauma or ligamentous injury.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-18T14:00:00Z', signedAt: '2026-06-18T15:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-007',
    caseId: 'demo-case-007', caseNumber: 'HG-DEMO-0007', patientName: 'Nur Sabrina Syazana',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Cervical lordosis maintained. Vertebral body heights preserved. Disc heights grossly preserved with minimal desiccation. No significant canal stenosis or cord compression. Cerebellar tonsils at level of foramen magnum without descent >5 mm.\n\nAbnormality — Central cervical and upper thoracic spinal cord (C2-C3 to ~T3):\n• Linear, fluid-filled cavity 12.0 cm longitudinal × 0.3 cm transverse within centre of spinal cord, without associated cord expansion.\n• T2 hyperintense signal matching CSF signal intensity.',
    impression: 'Most likely: Syringomyelia — ICD-11: 8B42.0 (cervicothoracic spinal cord, C2 to T3, without cord expansion). Hydromyelia and tumour-associated syrinx considered less likely.',
    suggestions: 'No immediate action unless acute neurological deterioration present. Clinical correlation with upper extremity sensory and motor examination. Contrast-enhanced MRI brain, cervical, and thoracic spine to rule out neoplastic aetiology or subtle Chiari malformation.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-20T13:00:00Z', signedAt: '2026-06-20T14:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-008',
    caseId: 'demo-case-008', caseNumber: 'HG-DEMO-0008', patientName: 'Raj Kumar a/l Subramaniam',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Cervical lordosis maintained. Vertebral body heights preserved. Atlantoaxial relationship within normal limits. Prevertebral soft tissue thickness normal. No acute fracture, subluxation, or prevertebral soft tissue swelling. No widening of predentate space.\n\nAbnormality — Anterior margins C5-C6 and C6-C7:\n• Minimal anterior osteophytic spurring (<0.3 cm). Normal bone density.',
    impression: 'Mild cervical spondylosis — ICD-11: FA80 (mild anterior osteophytosis at C5-C6 and C6-C7). Age-related degenerative remodelling. No acute traumatic osseous injury. Confidence: High.\n\nCaveat: Single lateral projection limits assessment of neural foramina, spinal canal, and cervicothoracic junction (T1).',
    suggestions: 'Minimal degenerative changes only. No acute injury identified. If neurological symptoms persist, consider additional projections or MRI for complete evaluation.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-21T13:00:00Z', signedAt: '2026-06-21T14:00:00Z',
    imageKeys: ['demo-img-001'],
  },
  {
    id: 'report-demo-009',
    caseId: 'demo-case-009', caseNumber: 'HG-DEMO-0009', patientName: 'Muhammad Aiman Hakim',
    radiologistId: 'rologist-001', radiologistName: 'Dr. Priya Nair',
    findings: 'Normal anatomy: Normal alignment of cervical spine. Vertebral body heights preserved. Craniovertebral junction and cerebellar tonsils within normal limits. No prevertebral soft tissue swelling, listhesis, fracture, or suspicious marrow replacement.\n\nAbnormality — C4-C5 intervertebral disc level:\n• Focal posterior disc protrusion/extrusion ~0.4 cm AP depth causing critical central canal stenosis.\n• Severe flattening and compression of the cervical spinal cord.\n• Focal intramedullary T2 hyperintensity at C4-C5 (cord oedema/myelomalacia).\n• Mild T2 hypointensity of C4-C5, C5-C6, C6-C7 discs — disc desiccation.',
    impression: 'Most likely: Cervical spinal stenosis with compressive myelopathy at C4-C5 — Grade 3 (ICD-11: FA81.0/8B90). Severe mechanical cord compression secondary to disc herniation with associated cord oedema/myelomalacia.',
    suggestions: 'Urgent neurosurgical or spine surgery consultation for evaluation of decompressive surgery. Detailed neurological exam for upper motor neuron signs. CT scan for preoperative bony planning. Cervical MRI with contrast if demyelinating/neoplastic process clinically suspected.',
    status: 'Verified / Signed Off',
    createdAt: '2026-06-23T13:00:00Z', signedAt: '2026-06-23T14:00:00Z',
    imageKeys: ['demo-img-001'],
  },
];

export const mockPatientRequests: PatientRequest[] = [
  {
    id: 'req-001',
    patientId: 'patient-001',
    patientName: 'Mohd Hafiz bin Ibrahim',
    mrn: 'MRN-2025-0001',
    requestType: 'Update',
    requestedBy: 'Dr. Sarah Chen',
    requestedById: 'doc-001',
    requestedByRole: 'Doctor',
    dateSubmitted: '2026-07-14T10:00:00Z',
    requestedChanges: { phone: '+60 12-999-8888', address: '25 Jalan Putra, 62000 Putrajaya' },
    reason: 'Patient reported change of address and new phone number during consultation.',
    status: 'Pending',
    remarks: '',
  },
];

export const mockAuditLogs: AuditLog[] = [
  {
    id: 'audit-001',
    userId: 'doc-001',
    userName: 'Dr. Sarah Chen',
    userRole: 'Doctor',
    action: 'PATIENT_REGISTER',
    target: 'patients/patient-003',
    details: 'Registered new patient: Raj Kumar a/l Subramaniam (MRN-2025-0003)',
    timestamp: '2026-07-08T08:30:00Z',
  },
  {
    id: 'audit-002',
    userId: 'doc-001',
    userName: 'Dr. Sarah Chen',
    userRole: 'Doctor',
    action: 'CASE_CREATED',
    target: 'cases/case-003',
    details: 'Created imaging case HG-2026-0003 for Raj Kumar - Lumbar Spine CT',
    timestamp: '2026-07-08T09:00:00Z',
  },
  {
    id: 'audit-003',
    userId: 'dept-001',
    userName: 'Nurul Aisyah',
    userRole: 'Radiology Department',
    action: 'CASE_SCHEDULED',
    target: 'cases/case-003',
    details: 'Scheduled case HG-2026-0003 for 2026-07-12 at Klinik Kesihatan Bangi',
    timestamp: '2026-07-09T10:00:00Z',
  },
  {
    id: 'audit-004',
    userId: 'rad-001',
    userName: 'Ahmad Razak',
    userRole: 'Radiographer',
    action: 'SCAN_UPLOADED',
    target: 'cases/case-003',
    details: 'Uploaded lumbar spine CT images for case HG-2026-0003',
    timestamp: '2026-07-12T11:45:00Z',
  },
  {
    id: 'audit-005',
    userId: 'rologist-001',
    userName: 'Dr. Priya Nair',
    userRole: 'Radiologist',
    action: 'REPORT_SIGNED',
    target: 'reports/report-001',
    details: 'Signed off diagnostic report for case HG-2026-0001',
    timestamp: '2026-06-03T15:00:00Z',
  },
  {
    id: 'audit-006',
    userId: 'admin-001',
    userName: 'Tan Wei Ming',
    userRole: 'Administrator',
    action: 'USER_LOGIN',
    target: 'users/admin-001',
    details: 'Administrator logged in from 192.168.1.100',
    timestamp: '2026-07-15T07:30:00Z',
  },
];

export const mockMobilePacsVans: MobilePacsVan[] = [
  {
    id: 'van-001',
    name: 'PACS Alpha',
    plateNumber: 'WKL 5501',
    equipment: ['X-Ray Unit', 'Portable CT Scanner'],
    currentClinicId: 'clinic-001',
    currentClinicName: 'Klinik Kesihatan Putrajaya',
    latitude: 2.9264,
    longitude: 101.6964,
    status: 'deployed',
    assignedRadiographerId: 'rad-001',
    assignedRadiographerName: 'Ahmad Razak',
  },
  {
    id: 'van-002',
    name: 'PACS Bravo',
    plateNumber: 'WKL 5502',
    equipment: ['MRI System', 'X-Ray Unit'],
    currentClinicId: 'clinic-002',
    currentClinicName: 'Klinik Kesihatan Cyberjaya',
    latitude: 2.9213,
    longitude: 101.6559,
    status: 'deployed',
  },
  {
    id: 'van-003',
    name: 'PACS Charlie',
    plateNumber: 'WKL 5503',
    equipment: ['X-Ray Unit'],
    latitude: 2.95,
    longitude: 101.72,
    status: 'idle',
  },
];

// Radiographer schedule profiles for AI Scheduler
// Generates realistic schedule data for the next 7 days
function generateScheduleSlots(bookedSlots: { date: string; time: string; caseId: string }[]): import('../types').RadioScheduleSlot[] {
  const slots: import('../types').RadioScheduleSlot[] = [];
  const today = new Date('2026-07-15');
  for (let d = 0; d < 7; d++) {
    const date = new Date(today);
    date.setDate(today.getDate() + d);
    const dateStr = date.toISOString().slice(0, 10);
    // Slots from 08:00 to 17:00, each 1 hour
    for (let h = 8; h < 17; h++) {
      const startTime = `${String(h).padStart(2, '0')}:00`;
      const endTime = `${String(h + 1).padStart(2, '0')}:00`;
      const booked = bookedSlots.find((s) => s.date === dateStr && s.time === startTime);
      slots.push({
        date: dateStr,
        startTime,
        endTime,
        booked: !!booked,
        caseId: booked?.caseId,
      });
    }
  }
  return slots;
}

export const mockRadioSchedules: RadioScheduleProfile[] = [
  {
    userId: 'rad-001',
    userName: 'Ahmad Razak',
    deployedClinicId: 'clinic-001',
    deployedClinicName: 'Klinik Kesihatan Putrajaya',
    supportedModalities: ['X-Ray', 'CT', 'MRI'],
    currentCaseload: 3,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '09:00', caseId: 'case-004' },
      { date: '2026-07-15', time: '10:00', caseId: 'case-003' },
      { date: '2026-07-15', time: '14:00', caseId: 'existing-1' },
      { date: '2026-07-16', time: '09:00', caseId: 'case-004' },
      { date: '2026-07-16', time: '11:00', caseId: 'existing-2' },
    ]),
  },
  {
    userId: 'rad-002',
    userName: 'Lim Mei Ling',
    deployedClinicId: 'clinic-002',
    deployedClinicName: 'Klinik Kesihatan Cyberjaya',
    supportedModalities: ['X-Ray', 'MRI', 'Ultrasound'],
    currentCaseload: 1,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '08:00', caseId: 'existing-3' },
      { date: '2026-07-16', time: '10:00', caseId: 'existing-4' },
    ]),
  },
  {
    userId: 'rad-003',
    userName: 'Kumaran Pillai',
    deployedClinicId: 'clinic-003',
    deployedClinicName: 'Klinik Kesihatan Bangi',
    supportedModalities: ['CT', 'X-Ray'],
    currentCaseload: 2,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '09:00', caseId: 'existing-5' },
      { date: '2026-07-15', time: '13:00', caseId: 'existing-6' },
      { date: '2026-07-16', time: '08:00', caseId: 'existing-7' },
      { date: '2026-07-16', time: '09:00', caseId: 'existing-8' },
    ]),
  },
  {
    userId: 'rad-004',
    userName: 'Farah Hanim',
    deployedClinicId: 'clinic-001',
    deployedClinicName: 'Klinik Kesihatan Putrajaya',
    supportedModalities: ['MRI', 'CT', 'X-Ray'],
    currentCaseload: 0,
    maxDailyCaseload: 6,
    leaveStatus: 'On Leave',
    shift: 'Morning (08:00–13:00)',
    schedule: generateScheduleSlots([]),
  },
  {
    userId: 'rad-005',
    userName: 'Wong Jia Hao',
    deployedClinicId: 'clinic-002',
    deployedClinicName: 'Klinik Kesihatan Cyberjaya',
    supportedModalities: ['X-Ray', 'Ultrasound', 'CT', 'MRI'],
    currentCaseload: 2,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '08:00', caseId: 'existing-9' },
      { date: '2026-07-15', time: '11:00', caseId: 'existing-10' },
      { date: '2026-07-16', time: '14:00', caseId: 'existing-11' },
    ]),
  },
  {
    userId: 'rad-006',
    userName: 'Zainal Abidin',
    deployedClinicId: 'clinic-004',
    deployedClinicName: 'Hospital Tanjong Karang',
    supportedModalities: ['X-Ray', 'CT', 'MRI', 'Ultrasound'],
    currentCaseload: 1,
    maxDailyCaseload: 8,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '09:00', caseId: 'existing-12' },
    ]),
  },
  {
    userId: 'rad-007',
    userName: 'Norhaslina Yusoff',
    deployedClinicId: 'clinic-004',
    deployedClinicName: 'Hospital Tanjong Karang',
    supportedModalities: ['MRI', 'CT', 'X-Ray'],
    currentCaseload: 0,
    maxDailyCaseload: 8,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([]),
  },
  {
    userId: 'rad-008',
    userName: 'Syed Farid Hassan',
    deployedClinicId: 'clinic-005',
    deployedClinicName: 'Klinik Kesihatan Ijok',
    supportedModalities: ['X-Ray', 'Ultrasound', 'CT'],
    currentCaseload: 0,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([]),
  },
  {
    userId: 'rad-009',
    userName: 'Tan Li Wen',
    deployedClinicId: 'clinic-006',
    deployedClinicName: 'Klinik Kesihatan Bestari Jaya',
    supportedModalities: ['X-Ray', 'MRI', 'CT', 'Ultrasound'],
    currentCaseload: 1,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([
      { date: '2026-07-15', time: '10:00', caseId: 'existing-13' },
    ]),
  },
  {
    userId: 'rad-010',
    userName: 'Anis Farhanah',
    deployedClinicId: 'clinic-007',
    deployedClinicName: 'Klinik Kesihatan Bukit Cherakah',
    supportedModalities: ['X-Ray', 'CT', 'Ultrasound'],
    currentCaseload: 0,
    maxDailyCaseload: 6,
    leaveStatus: 'Active',
    shift: 'Day (08:00–17:00)',
    schedule: generateScheduleSlots([]),
  },
];

// Enrich cases with disease, severity, and bodyRegion fields
const caseEnrichment: Record<string, { disease: string; severity: 'Mild' | 'Moderate' | 'Severe' | 'Critical'; bodyRegion: string }> = {
  'case-001': { disease: 'Persistent Cough', severity: 'Moderate', bodyRegion: 'Chest' },
  'case-002': { disease: 'Recurrent Migraines', severity: 'Moderate', bodyRegion: 'Head' },
  'case-003': { disease: 'Post-Surgical Follow-up', severity: 'Moderate', bodyRegion: 'Lumbar Spine' },
  'case-004': { disease: 'Epigastric Pain', severity: 'Moderate', bodyRegion: 'Abdomen' },
  'case-005': { disease: 'ACL Injury', severity: 'Moderate', bodyRegion: 'Knee' },
  'case-006': { disease: 'Lumbar Disc Herniation', severity: 'Moderate', bodyRegion: 'Lumbar Spine' },
  'case-007': { disease: 'Osteoarthritis', severity: 'Mild', bodyRegion: 'Knee' },
  'case-008': { disease: 'Suspected Lung Cancer', severity: 'Critical', bodyRegion: 'Chest' },
  'case-009': { disease: 'Brain Tumor Investigation', severity: 'Critical', bodyRegion: 'Head' },
  'case-010': { disease: 'Wrist Fracture', severity: 'Moderate', bodyRegion: 'Wrist' },
  'case-011': { disease: 'Stroke Assessment', severity: 'Critical', bodyRegion: 'Head' },
  'case-012': { disease: 'Knee Ligament Injury', severity: 'Moderate', bodyRegion: 'Knee' },
  'case-013': { disease: 'Tuberculosis Screening', severity: 'Severe', bodyRegion: 'Chest' },
  'case-014': { disease: 'Head Trauma', severity: 'Critical', bodyRegion: 'Head' },
  'case-015': { disease: 'Kidney Stone', severity: 'Moderate', bodyRegion: 'Abdomen' },
  'case-016': { disease: 'Ankle Sprain', severity: 'Mild', bodyRegion: 'Ankle' },
  'case-017': { disease: 'Pulmonary Embolism', severity: 'Critical', bodyRegion: 'Chest' },
  'case-018': { disease: 'Abdominal Pain', severity: 'Moderate', bodyRegion: 'Abdomen' },
  'case-019': { disease: 'Pneumonia', severity: 'Moderate', bodyRegion: 'Chest' },
  'case-020': { disease: 'Multiple Sclerosis', severity: 'Severe', bodyRegion: 'Head' },
  'case-021': { disease: 'Chronic Back Pain', severity: 'Mild', bodyRegion: 'Lumbar Spine' },
  'case-022': { disease: 'Liver Lesion', severity: 'Severe', bodyRegion: 'Abdomen' },
  'case-023': { disease: 'Stroke Follow-Up', severity: 'Moderate', bodyRegion: 'Head' },
  'case-024': { disease: 'Sinus Disease', severity: 'Mild', bodyRegion: 'Head' },
  'case-025': { disease: 'Cervical Disc Compression', severity: 'Moderate', bodyRegion: 'Cervical Spine' },
};

mockCases.forEach((c) => {
  const enrichment = caseEnrichment[c.id];
  if (enrichment) {
    (c as any).disease = enrichment.disease;
    (c as any).severity = enrichment.severity;
    (c as any).bodyRegion = enrichment.bodyRegion;
  }
});
