name: Test Self Hosted Runner

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Test runner
        run: |
          echo "Runner is working"
          hostname
          whoami
          pwd
          ansible-playbook --version
          docker --version
